### ISSUE TITLE
[ASC] `ArrayBuffer` does not have property `decode`

### ISSUE THREAD

**Issue by AuHau** [wapc/widl-codegen-js#14]
If you generate AssemblyScript's WIDL with:

```
interface {
  someFunction(): bytes
}
```

The Host's binding in `module.ts` will get generated with:

```ts
export class Host {
  binding: string;

  constructor(binding: string = "default") {
    this.binding = binding;
  }

  getChunk(): ArrayBuffer {
    // ...
    const payload = hostCall(...);
    const decoder = new Decoder(payload);
    return ArrayBuffer.decode(decoder);
  }
}
```

Yet the `ArrayBuffer` (which follows the JS's [`ArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) API) does not have `decode` function.

**Comment by pkedy** [comment]
Thanks for reporting this, @AuHau !

Try running `wapc upgrade` and try it again. Note that `@wapc/as-guest` now requires return types to be wrapped with `Result<T>`.

**Comment by AuHau** [comment]
It is fixed now! Awesome, thanks!
